import { buildRenderOperatorChecklist } from "./operatorChecklist";
import { parseBuzzardApiFromRenderYaml } from "./parseRenderService";
import { validateRenderBlueprint } from "@/lib/production-storage-preflight/renderBlueprintValidation";
import { buildRenderPersistenceLiveStatus } from "@/lib/render-persistence-evidence-bridge/persistenceStatus";

export function buildRenderPersistentDiskOperatorGuideMarkdown(): string {
  const parsed = parseBuzzardApiFromRenderYaml();
  const blueprint = validateRenderBlueprint();
  const live = buildRenderPersistenceLiveStatus();
  const checklist = buildRenderOperatorChecklist();
  const apiUrl = process.env.BUZZARD_API_URL?.replace(/\/$/, "") || parsed.defaultApiBaseUrl || "(set BUZZARD_API_URL)";
  const healthUrl = `${apiUrl}/api/health/db`;

  const lines: string[] = [
    "# BUZZARD — Render Persistent Disk Operator Guide",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    "## RENDER DASHBOARD ACTION REQUIRED",
    "",
    "**Cursor does not have access to your Render Dashboard.** Nothing below is marked done until you perform the steps and run verification.",
    "",
    "GOLDEN RULE: **RENDER BLUEPRINT ≠ LIVE RENDER** — `render.yaml` disk config does not prove the disk is mounted at runtime.",
    "",
    "---",
    "",
    "## Repository facts (from `render.yaml`)",
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| Service name | \`${parsed.serviceName}\` |`,
    `| Disk name | \`${parsed.diskName ?? "—"}\` |`,
    `| Mount path (blueprint) | \`${parsed.mountPath ?? "—"}\` |`,
    `| Disk size (blueprint) | \`${parsed.diskSizeGB ?? "—"} GB\` |`,
    `| BUZZARD_DB_PATH (blueprint) | \`${parsed.dbPathEnv ?? "—"}\` |`,
    `| BUZZARD_BACKUP_DIR (blueprint) | \`${parsed.backupDirEnv ?? "—"}\` |`,
    `| Health check (service) | \`${parsed.healthCheckPath ?? "/api/health"}\` |`,
    `| DB health URL (derive) | \`${healthUrl}\` |`,
    "",
    `BLUEPRINT_CONFIGURATION: **${blueprint.BLUEPRINT_CONFIGURATION === "PASS" ? "CONFIGURED" : "BLOCKED"}**`,
    "",
    "---",
    "",
    "## Operator steps",
    "",
    "### STEP 1 — Render Dashboard login",
    "Open [Render Dashboard](https://dashboard.render.com/) and sign in.",
    "",
    "### STEP 2 — Find Buzzard API service",
    `Service name from repository: **\`${parsed.serviceName}\`** (do not use a different name unless your Dashboard differs).`,
    "",
    "### STEP 3 — Settings → Disks",
    `Open **Settings → Disks** for \`${parsed.serviceName}\`.`,
    "",
    "### STEP 4 — Create Persistent Disk",
    "- **Mount Path:** `/var/data`",
    "- **Disk Size:** at least **1 GB**",
    "",
    "### STEP 5 — Environment variables",
    "Confirm in Render Dashboard:",
    "- `BUZZARD_DB_PATH=/var/data/buzzard.db`",
    "- `BUZZARD_BACKUP_DIR=/var/data/backups`",
    "",
    "### STEP 6 — Save",
    "Save disk and environment changes.",
    "",
    "### STEP 7 — Deploy (operator only)",
    "Trigger **Deploy** / **Manual Deploy** from Render. **Cursor does not deploy.**",
    "",
    "### STEP 8 — Verify DB health",
    `After deploy succeeds, run from your workstation:`,
    "",
    "```bash",
    `BUZZARD_API_URL=${apiUrl} npm run verify:render-persistence`,
    "```",
    "",
    `Or curl: \`curl -sS ${healthUrl}\``,
    "",
    "Expected when live disk is active:",
    "- `persistent: true`",
    "- `path` contains `/var/data/buzzard.db`",
    "",
    "---",
    "",
    "## PHASE 5 — Restart persistence test (operator)",
    "",
    "1. Run `npm run verify:render-persistence` (baseline).",
    "2. In Render Dashboard: **Manual Restart** on `buzzard-api`.",
    "3. Wait until service is live.",
    "4. Run `npm run verify:render-persistence` again.",
    "5. Confirm `persistent=true` and path still `/var/data/buzzard.db`.",
    "6. Register restart evidence via render persistence evidence bridge (operator attestation).",
    "",
    "If restart breaks persistence: `LIVE_RESTART_PERSISTENCE=BLOCKED` or `UNVERIFIED_EXTERNAL`.",
    "",
    "---",
    "",
    "## PHASE 6 — Backup (operator on Render shell)",
    "",
    "Use existing script only: `npm run backup:db` with `BUZZARD_DB_PATH` and `BUZZARD_BACKUP_DIR` pointing at `/var/data`.",
    "Cursor **will not** claim backup PASS without `RENDER_BACKUP` evidence.",
    "",
    "---",
    "",
    "## PHASE 7 — Restore safety",
    "",
    "Use `scripts/restore-db.mjs` only with existing guards.",
    "Production restore requires `BUZZARD_ALLOW_PRODUCTION_RESTORE=1` — do not bypass.",
    "",
    "---",
    "",
    "## Current live status (evidence SSOT)",
    "",
    `| Check | Status |`,
    `|-------|--------|`,
    `| LIVE_RENDER_DISK | ${live.LIVE_RENDER_DISK} |`,
    `| LIVE_DB_PATH | ${live.LIVE_DB_PATH} |`,
    `| LIVE_DB_HEALTH | ${live.LIVE_DB_HEALTH} |`,
    `| LIVE_RESTART_PERSISTENCE | ${live.LIVE_RESTART_PERSISTENCE} |`,
    `| LIVE_BACKUP | ${live.LIVE_BACKUP} |`,
    `| LIVE_RESTORE | ${live.LIVE_RESTORE} |`,
    `| PERSISTENCE | ${live.PERSISTENCE} |`,
    "",
    "PRODUCTION / GO_LIVE remain **BLOCKED** until full external chain completes. **SALES_ENABLED=0**.",
    "",
    "---",
    "",
    "## Operator checklist",
    "",
    "| Done | Step | CURRENT STATUS | EVIDENCE | BLOCKER |",
    "|------|------|----------------|----------|---------|",
  ];

  for (const item of checklist) {
    lines.push(
      `| ${item.checked ? "x" : " "} | ${item.label} | ${item.currentStatus} | ${item.evidence} | ${item.blocker} |`,
    );
  }

  lines.push("", "---", "", "## Commands", "", "```bash", "npm run status:render-persistence", "npm run preflight:render-persistence", "npm run verify:render-persistence", "npm run gate:render-persistence", "```", "");

  return lines.join("\n");
}
