/** Icon keys for the 41 main categories (CategoryIcon names). */
export const mainCategoryIcons: Record<string, string> = {
  "cat-01": "fashion",
  "cat-02": "care",
  "cat-03": "care",
  "cat-04": "tools",
  "cat-05": "car",
  "cat-06": "pet",
  "cat-07": "garden",
  "cat-08": "tools",
  "cat-09": "tools",
  "cat-10": "home",
  "cat-11": "home",
  "cat-12": "electronics",
  "cat-13": "appliance",
  "cat-14": "sport",
  "cat-15": "fashion",
  "cat-16": "fashion",
  "cat-17": "baby",
  "cat-18": "baby",
  "cat-19": "sport",
  "cat-20": "pet",
  "cat-21": "build",
  "cat-22": "electronics",
  "cat-23": "build",
  "cat-24": "appliance",
  "cat-25": "food",
  "cat-26": "pet",
  "cat-27": "care",
  "cat-28": "tools",
  "cat-29": "box",
  "cat-30": "tools",
  "cat-31": "shield",
  "cat-32": "fashion",
  "cat-33": "garden",
  "cat-34": "star",
  "cat-35": "home",
  "cat-36": "electronics",
  "cat-37": "electronics",
  "cat-38": "electronics",
  "cat-39": "car",
  "cat-40": "electronics",
  "cat-41": "star",
};

export function getMainCategoryIcon(id: string): string {
  return mainCategoryIcons[id] ?? "star";
}
