const CHANNELS = Object.freeze({
  TEXT: "TEXT",
  VOICE: "VOICE",
  PHONE: "PHONE",
});

const INTENTS = Object.freeze({
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  PRODUCT_INFORMATION: "PRODUCT_INFORMATION",
  PRICE_CHECK: "PRICE_CHECK",
  STOCK_CHECK: "STOCK_CHECK",
  VEHICLE_LOOKUP: "VEHICLE_LOOKUP",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ORDER_STATUS: "ORDER_STATUS",
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_CANCEL: "ORDER_CANCEL",
  RETURN_REQUEST: "RETURN_REQUEST",
  REFUND_STATUS: "REFUND_STATUS",
  DELIVERY_STATUS: "DELIVERY_STATUS",
  SUPPLIER_QUERY: "SUPPLIER_QUERY",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
  COMPLAINT: "COMPLAINT",
  PAYMENT_QUERY: "PAYMENT_QUERY",
  ACCOUNT_QUERY: "ACCOUNT_QUERY",
  MARKETPLACE_QUERY: "MARKETPLACE_QUERY",
  CATEGORY_QUERY: "CATEGORY_QUERY",
  GENERAL_QUERY: "GENERAL_QUERY",
  HUMAN_AGENT_REQUEST: "HUMAN_AGENT_REQUEST",
  PHONE_CALL_REQUEST: "PHONE_CALL_REQUEST",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  SECURITY_EVENT: "SECURITY_EVENT",
});

const RISK = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

const REQUEST_STATE = Object.freeze({
  RECEIVED: "RECEIVED",
  AUTHENTICATED: "AUTHENTICATED",
  CLASSIFIED: "CLASSIFIED",
  AUTHORIZED: "AUTHORIZED",
  PLANNED: "PLANNED",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  EXECUTING: "EXECUTING",
  VALIDATING: "VALIDATING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  ESCALATED: "ESCALATED",
});

const CONVERSATION_STATUS = Object.freeze({
  NEW: "NEW",
  ACTIVE: "ACTIVE",
  WAITING: "WAITING",
  APPROVAL: "APPROVAL",
  HANDOFF: "HANDOFF",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

const VOICE_STATE = Object.freeze({
  CONNECTING: "CONNECTING",
  LISTENING: "LISTENING",
  THINKING: "THINKING",
  SPEAKING: "SPEAKING",
  INTERRUPTED: "INTERRUPTED",
  ENDING: "ENDING",
  ENDED: "ENDED",
  ERROR: "ERROR",
});

const TASK_STATUS = Object.freeze({
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  WAITING: "WAITING",
  WAITING_APPROVAL: "WAITING_APPROVAL",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
});

const PROVIDER_HEALTH = Object.freeze({
  HEALTHY: "HEALTHY",
  DEGRADED: "DEGRADED",
  DOWN: "DOWN",
  NOT_CONFIGURED: "NOT_CONFIGURED",
});

const LANGUAGES = Object.freeze(["de", "en", "tr", "ar"]);

module.exports = {
  CHANNELS,
  INTENTS,
  RISK,
  REQUEST_STATE,
  CONVERSATION_STATUS,
  VOICE_STATE,
  TASK_STATUS,
  PROVIDER_HEALTH,
  LANGUAGES,
};
