import { buildMasterFinalCompletionReport } from "./masterFinalCompletionReport";

export function buildFinalGoLiveHandoffMarkdown(): string {
  const report = buildMasterFinalCompletionReport();
  const lines: string[] = [
    "# BUZZARD Final Go-Live Handoff",
    "",
    `Generated: ${report.generatedAt}`,
    "",
    "## Execution order (mandatory)",
    "A AI → B Memory/Approval/Exception → C Marketplace → D E2E → E Security → F Go-Live",
    "",
    "### 1. Software complete status",
    `- SOFTWARE: ${report.scoreboard.SOFTWARE}`,
    `- INTERNAL_INTEGRATION: ${report.scoreboard.INTERNAL_INTEGRATION}`,
    "",
    "### 2. AI status",
    `- AI: ${report.scoreboard.AI}`,
    `- Phase A: ${report.phases.find((p) => p.phase === "A")?.status}`,
    "",
    "### 3. Memory status",
    `- MEMORY: ${report.scoreboard.MEMORY}`,
    "",
    "### 4. Human Approval status",
    `- HUMAN_APPROVAL: ${report.scoreboard.HUMAN_APPROVAL}`,
    "",
    "### 5. Exception status",
    `- EXCEPTION: ${report.scoreboard.EXCEPTION}`,
    "",
    "### 6. Marketplace status",
    `- MARKETPLACE: ${report.scoreboard.MARKETPLACE}`,
    "",
    "### 7. E2E status",
    `- E2E_TEST: ${report.scoreboard.E2E_TEST}`,
    "",
    "### 8. Security status",
    `- SECURITY: ${report.scoreboard.SECURITY}`,
    "",
    "### 9. Provider status",
    `- PAYMENT: ${report.scoreboard.PAYMENT}`,
    `- CARRIER: ${report.scoreboard.CARRIER}`,
    `- RETURNS: ${report.scoreboard.RETURNS}`,
    `- SUPPLIER: ${report.scoreboard.SUPPLIER}`,
    "",
    "### 10. 35-market status",
    `- 35_MARKETS: ${report.scoreboard["35_MARKETS"]}`,
    "",
    "### 11. Customs status",
    `- CUSTOMS: ${report.scoreboard.CUSTOMS}`,
    "",
    "### 12. Persistence status",
    `- PERSISTENCE: ${report.scoreboard.PERSISTENCE}`,
    "",
    "### 13. Backup status",
    `- BACKUP: ${report.scoreboard.BACKUP}`,
    "",
    "### 14. External blockers",
    ...report.blockers.slice(0, 15).map((b) => `- ${b}`),
    "",
    "### 15. Required human actions",
    ...report.humanActionMatrix.slice(0, 12).map(
      (h) =>
        `- **${h.provider}**: ${h.action} (evidence: ${h.requiredEvidence}, verify: ${h.verification}, status: ${h.status})`,
    ),
    "",
    "### 16. Required evidence",
    "- EXTERNAL_LIVE only (no MOCK/SANDBOX/UNIT_TEST as production)",
    "",
    "### 17. First order gate",
    `- FIRST_ORDER: ${report.scoreboard.FIRST_ORDER}`,
    "",
    "### 18. Post-order validation",
    `- POST_ORDER: blocked until first order evidence`,
    "",
    "### 19. Observation period",
    `- OBSERVATION: ${report.scoreboard.OBSERVATION}`,
    "",
    "### 20. Final go-live procedure",
    `- PRODUCTION: ${report.scoreboard.PRODUCTION}`,
    `- GO_LIVE: ${report.scoreboard.GO_LIVE}`,
    `- SALES_ENABLED: ${report.SALES_ENABLED} (operator must explicitly enable)`,
    "",
    `FAKE_PRODUCTION_EVIDENCE: ${report.fakeProductionEvidence}`,
    `REAL_SIDE_EFFECTS: ${Object.values(report.sideEffects).reduce((a, b) => a + b, 0)}`,
    "",
    `NEXT_HUMAN_ACTION: ${report.nextHumanAction}`,
  ];
  return lines.join("\n");
}
