import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "server/__tests__/**/*.test.mjs",
      "lib/i18n/**/*.test.ts",
      "lib/market-engine/**/*.test.ts",
      "lib/product-engine/**/*.test.ts",
      "lib/supplier-engine/**/*.test.ts",
      "lib/supplier-engine/internationalOrigin.test.ts",
      "lib/pricing-engine/**/*.test.ts",
      "lib/inventory-engine/**/*.test.ts",
      "lib/order-engine/**/*.test.ts",
      "lib/trade-route-fulfillment/**/*.test.ts",
      "lib/customs-fulfillment-gate/**/*.test.ts",
      "lib/fulfillment-control-tower/**/*.test.ts",
      "lib/supplier-order-readiness/**/*.test.ts",
      "lib/supplier-order-rehearsal/**/*.test.ts",
      "lib/supplier-production-validation/**/*.test.ts",
      "lib/supplier-order-activation/**/*.test.ts",
      "lib/supplier-production-order-validation/**/*.test.ts",
      "lib/supplier-production-order-arming/**/*.test.ts",
      "lib/supplier-first-production-order/**/*.test.ts",
      "lib/supplier-controlled-go-live/**/*.test.ts",
      "lib/supplier-go-live-observation/**/*.test.ts",
      "lib/supplier-inter-cars-production-access/**/*.test.ts",
      "lib/first-order-fulfillment/**/*.test.ts",
      "lib/tracking-fulfillment/**/*.test.ts",
      "lib/payment-production/**/*.test.ts",
      "lib/carrier-production/**/*.test.ts",
      "lib/ai-production/**/*.test.ts",
      "lib/returns-refunds-production/**/*.test.ts",
      "lib/final-production-go-live/**/*.test.ts",
      "lib/production-access/**/*.test.ts",
      "lib/production-kill-switch/**/*.test.ts",
      "lib/production-completion/**/*.test.ts",
      "lib/final-closure/**/*.test.ts",
      "lib/final-operations/**/*.test.ts",
      "lib/marketplace-engine/**/*.test.ts",
      "lib/returns-engine/**/*.test.ts",
      "lib/ai-orchestrator/**/*.test.ts",
      "lib/ai-workers/**/*.test.ts",
      "lib/analytics/**/*.test.ts",
      "lib/commerce/**/*.test.ts",
    ],
    globals: false,
    testTimeout: 15000,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
    },
  },
});
