"""Buzzard project — local URLs and ports."""

BUZZARD_HOST = "127.0.0.1"
BUZZARD_API_PORT = 8000
BUZZARD_VOICE_PORT = 8787
BUZZARD_API_URL = f"http://{BUZZARD_HOST}:{BUZZARD_API_PORT}"
BUZZARD_VOICE_URL = f"http://{BUZZARD_HOST}:{BUZZARD_VOICE_PORT}"

# Legacy aliases (gizli)
GIZLI_HOST = BUZZARD_HOST
GIZLI_API_PORT = BUZZARD_API_PORT
GIZLI_VOICE_PORT = BUZZARD_VOICE_PORT
GIZLI_API_URL = BUZZARD_API_URL
GIZLI_VOICE_URL = BUZZARD_VOICE_URL
