from .vehicle_needs import VEHICLE_NEED_SYSTEMS

# This seed deliberately describes the NEEDS of a vehicle, not a flat product list.
# It is expandable and designed to be merged with TecDoc/OEM/supplier taxonomies.

MASTER_SYSTEMS = [
("engine","Motor & Motor İç Sistemleri"),
("lubrication","Yağlama Sistemi"),
("timing","Triger & Motor Zamanlama"),
("fuel","Yakıt Sistemi & Enjeksiyon"),
("air-intake","Hava Girişi & Emme"),
("turbo","Turbo & Şarj Havası"),
("cooling","Soğutma Sistemi"),
("ignition","Ateşleme Sistemi"),
("diesel-injection","Dizel Enjeksiyon"),
("exhaust","Egzoz Sistemi"),
("emissions","Emisyon & Arıtma"),
("manual-transmission","Manuel Şanzıman"),
("automatic-transmission","Otomatik Şanzıman"),
("dual-clutch","Çift Kavramalı Şanzıman"),
("clutch","Debriyaj Sistemi"),
("torque-converter","Tork Konvertörü"),
("transfer-case","Transfer Kutusu"),
("differential","Diferansiyel"),
("driveshaft","Kardan & Aks Aktarma"),
("brakes","Fren Sistemi"),
("suspension","Süspansiyon & Amortisör"),
("steering","Direksiyon Sistemi"),
("wheel-hubs","Porya & Tekerlek Göbeği"),
("bearings","Rulmanlar"),
("axles","Akslar"),
("battery","Akü & Enerji Depolama"),
("starting","Marş Sistemi"),
("charging","Şarj & Alternatör Sistemi"),
("fuses-relays","Sigorta & Röle"),
("wiring","Kablo & Elektrik Tesisatı"),
("ecu","ECU & Kontrol Modülleri"),
("sensors","Sensörler"),
("actuators","Aktüatörler"),
("lighting","Aydınlatma"),
("infotainment","Multimedya & Bilgi-Eğlence"),
("driver-assistance","ADAS & Sürücü Destek"),
("engine-cooling","Motor Soğutma"),
("air-conditioning","Klima"),
("heating","Kalorifer & Isıtma"),
("ventilation","Havalandırma"),
("body-panels","Kaporta & Gövde Panelleri"),
("bumpers","Tamponlar"),
("doors","Kapılar & Kapı Donanımı"),
("hood","Kaput"),
("tailgate","Bagaj Kapağı"),
("mirrors","Aynalar"),
("glass","Cam Sistemleri"),
("wipers","Silecek & Cam Yıkama"),
("seals","Contalar & Sızdırmazlık"),
("roof","Tavan & Açılır Tavan"),
("undercarriage","Alt Gövde & Koruma"),
("seats","Koltuklar"),
("restraint-systems","Emniyet Kemeri & Airbag"),
("dashboard","Gösterge Paneli"),
("controls","Kumandalar & Düğmeler"),
("flooring","Paspas & Zemin"),
("interior-trim","İç Trim"),
("comfort","Konfor Sistemleri"),
("tyres","Lastikler"),
("wheels","Jantlar"),
("rims","Jant Aksesuarları"),
("tpms","TPMS"),
("wheel-fasteners","Bijon & Tekerlek Bağlantıları"),
("repair-kits","Lastik Tamir & Acil Durum"),
("engine-oils","Motor Yağları"),
("transmission-oils","Şanzıman Yağları"),
("differential-oils","Diferansiyel Yağları"),
("brake-fluids","Fren Hidrolikleri"),
("coolants","Antifriz & Soğutma Sıvıları"),
("washer-fluids","Cam Suları"),
("greases","Gresler"),
("additives","Katkı Maddeleri"),
("filters","Filtreler"),
("belts","Kayışlar"),
("hoses","Hortumlar"),
("spark-plugs","Buji"),
("glow-plugs","Kızdırma Bujileri"),
("lamps","Ampuller & Lambalar"),
("wiper-blades","Silecek Süpürgeleri"),
("service-kits","Bakım & Servis Kitleri"),
("inspection-tools","Servis & Atölye Ekipmanları"),
("diagnostics","Diagnostik & Test Cihazları"),
("workshop-consumables","Atölye Sarf Malzemeleri"),
("cargo","Bagaj & Taşıma"),
("roof-transport","Tavan Taşıma"),
("towing","Çeki & Römork"),
("phone-mounts","Telefon & Mobilite Aksesuarları"),
("security","Araç Güvenliği"),
("charging-accessories","Şarj Aksesuarları"),
("hybrid-systems","Hibrit Sistemler"),
("high-voltage-battery","Yüksek Voltaj Bataryası"),
("ev-motor","Elektrikli Motor"),
("inverter","İnverter"),
("onboard-charger","Araç İçi Şarj"),
("charging-cables","Şarj Kabloları"),
("thermal-management","EV/Hibrit Termal Yönetim"),
("van-parts","Hafif Ticari Araç Parçaları"),
("truck-parts","Kamyon Parçaları"),
("bus-parts","Otobüs Parçaları"),
("trailer-parts","Römork & Treyler Parçaları"),
("motorcycle-parts","Motosiklet & Scooter Parçaları"),
("atv-parts","ATV & Quad Parçaları"),
("tractor-parts","Traktör & Tarım Makinesi Parçaları"),
("classic-car-parts","Klasik & Oldtimer Parçaları")
]
