from .database import IntelligenceDB

# Original TR seed (100+ categories) — legacy intelligence pack
SEED_CATEGORIES = [
    "Otomotiv", "Tarım Makineleri ve Ekipmanları", "Lastik ve Jant",
    "Elektronik", "Bilgisayar", "Telefon ve Aksesuarları", "Ev Aletleri",
    "Beyaz Eşya", "Ev ve Yaşam", "Mobilya", "Mutfak", "Bahçe",
    "Hırdavat", "El Aletleri", "İnşaat", "Temizlik", "Kozmetik",
    "Kişisel Bakım", "Giyim", "Ayakkabı", "Çanta ve Aksesuar",
    "Tekstil", "Bebek Ürünleri", "Çocuk Ürünleri", "Oyuncak", "Hobi",
    "Spor", "Kamp ve Outdoor", "Bisiklet", "Evcil Hayvan",
    "Kırtasiye", "Ofis", "Kitap", "Müzik", "Fotoğraf", "Video",
    "Oyun", "Oyun Konsolları", "Bilgisayar Parçaları",
    "Güvenlik Sistemleri", "Aydınlatma", "Elektrik Malzemeleri",
    "Güneş Enerjisi", "Enerji ve Batarya", "Yedek Parça", "Motosiklet",
    "Tekne ve Denizcilik", "Karavan", "Seyahat", "Valiz ve Seyahat Aksesuarları",
    "Takı", "Saat", "Gözlük", "Hediyelik", "Dekorasyon", "Ev Tekstili",
    "Yatak ve Uyku", "Banyo", "Depolama ve Organizasyon",
    "Bebek Bakım", "Anne Ürünleri", "Gıda", "İçecek", "Kahve ve Çay",
    "Endüstriyel Ürünler", "İş Güvenliği", "İş Kıyafetleri",
    "Restoran Ekipmanları", "Otel Ekipmanları", "Tarım Ürünleri",
    "Sulama", "Seracılık", "Bahçe Makineleri", "Orman ve Ağaç Ekipmanları",
    "Yapıştırıcılar", "Boya", "Yapı Malzemeleri", "Isıtma", "Klima",
    "Havalandırma", "Su Tesisatı", "Banyo Tesisatı", "Akıllı Ev", "IoT",
    "Bebek Elektroniği", "Optik", "Laboratuvar Ürünleri",
    "Endüstriyel Otomasyon", "Robotik", "3D Yazıcı ve Filament",
    "Drone", "Koleksiyon", "Sanat ve El İşi", "Parti ve Organizasyon",
    "Mevsimsel Ürünler", "Okul Ürünleri", "Otomasyon Yazılımları",
    "İşletme ve Ofis Teknolojileri", "Ambalaj", "Lojistik Ekipmanları",
    "Depo Ekipmanları", "Profesyonel Temizlik", "Medya ve İçerik Ekipmanları",
]
