/** Return & Recovery Engine — central constants (no duplicate engines). */

const RETURN_STATES = Object.freeze({
  DRAFT: "DRAFT",
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  RETURN_LABEL_REQUIRED: "RETURN_LABEL_REQUIRED",
  IN_TRANSIT: "IN_TRANSIT",
  RECEIVED: "RECEIVED",
  INSPECTION_REQUIRED: "INSPECTION_REQUIRED",
  INSPECTED: "INSPECTED",
  REFUND_PENDING: "REFUND_PENDING",
  REFUNDED: "REFUNDED",
  SUPPLIER_RECOVERY_PENDING: "SUPPLIER_RECOVERY_PENDING",
  SUPPLIER_CREDIT_PENDING: "SUPPLIER_CREDIT_PENDING",
  SUPPLIER_REFUND_CONFIRMED: "SUPPLIER_REFUND_CONFIRMED",
  SUPPLIER_CREDIT_CONFIRMED: "SUPPLIER_CREDIT_CONFIRMED",
  CLOSED: "CLOSED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
});

const ITEM_CONDITIONS = Object.freeze({
  UNKNOWN: "UNKNOWN",
  NEW: "NEW",
  UNOPENED: "UNOPENED",
  OPENED: "OPENED",
  USED: "USED",
  DAMAGED: "DAMAGED",
  DEFECTIVE: "DEFECTIVE",
  WRONG_ITEM: "WRONG_ITEM",
  MISSING_PARTS: "MISSING_PARTS",
  PACKAGING_DAMAGED: "PACKAGING_DAMAGED",
  NOT_RESALEABLE: "NOT_RESALEABLE",
  RESELLABLE: "RESELLABLE",
});

const RETURN_REASONS = Object.freeze({
  CUSTOMER_CHANGE_OF_MIND: "CUSTOMER_CHANGE_OF_MIND",
  CUSTOMER_WRONG_ORDER: "CUSTOMER_WRONG_ORDER",
  CUSTOMER_WRONG_SIZE: "CUSTOMER_WRONG_SIZE",
  CUSTOMER_WRONG_PRODUCT: "CUSTOMER_WRONG_PRODUCT",
  PRODUCT_DEFECT: "PRODUCT_DEFECT",
  PRODUCT_DAMAGED: "PRODUCT_DAMAGED",
  WRONG_PRODUCT_SENT: "WRONG_PRODUCT_SENT",
  MISSING_PARTS: "MISSING_PARTS",
  SUPPLIER_ERROR: "SUPPLIER_ERROR",
  TRANSPORT_DAMAGE: "TRANSPORT_DAMAGE",
  DUPLICATE_ORDER: "DUPLICATE_ORDER",
  OTHER: "OTHER",
});

const LIABILITY_TYPES = Object.freeze({
  CUSTOMER: "CUSTOMER",
  BUZZARD: "BUZZARD",
  SUPPLIER: "SUPPLIER",
  CARRIER: "CARRIER",
  UNKNOWN: "UNKNOWN",
});

const SUPPLIER_RECOVERY_STATUS = Object.freeze({
  NOT_APPLICABLE: "NOT_APPLICABLE",
  PENDING: "PENDING",
  REQUESTED: "REQUESTED",
  PARTIALLY_CONFIRMED: "PARTIALLY_CONFIRMED",
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
  DISPUTED: "DISPUTED",
});

const CREDIT_NOTE_STATUS = Object.freeze({
  NOT_REQUESTED: "NOT_REQUESTED",
  REQUESTED: "REQUESTED",
  RECEIVED: "RECEIVED",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
  DISPUTED: "DISPUTED",
});

const RETURN_SHIPPING_PAID_BY = Object.freeze({
  CUSTOMER: "CUSTOMER",
  BUZZARD: "BUZZARD",
  SUPPLIER: "SUPPLIER",
  CARRIER: "CARRIER",
  UNKNOWN: "UNKNOWN",
});

const SUPPLIER_RECOVERY_EVENT_TYPES = Object.freeze({
  REFUND: "REFUND",
  CREDIT_NOTE: "CREDIT_NOTE",
});

const AUDIT_ACTIONS = Object.freeze({
  RETURN_CREATED: "RETURN_CREATED",
  RETURN_APPROVED: "RETURN_APPROVED",
  RETURN_RECEIVED: "RETURN_RECEIVED",
  RETURN_INSPECTED: "RETURN_INSPECTED",
  CUSTOMER_REFUND_CALCULATED: "CUSTOMER_REFUND_CALCULATED",
  CUSTOMER_REFUND_REQUESTED: "CUSTOMER_REFUND_REQUESTED",
  CUSTOMER_REFUND_BLOCKED: "CUSTOMER_REFUND_BLOCKED",
  SUPPLIER_CLAIM_CREATED: "SUPPLIER_CLAIM_CREATED",
  SUPPLIER_CLAIM_REQUESTED: "SUPPLIER_CLAIM_REQUESTED",
  SUPPLIER_REFUND_CONFIRMED: "SUPPLIER_REFUND_CONFIRMED",
  SUPPLIER_CREDIT_REQUESTED: "SUPPLIER_CREDIT_REQUESTED",
  SUPPLIER_CREDIT_RECEIVED: "SUPPLIER_CREDIT_RECEIVED",
  SUPPLIER_CREDIT_VERIFIED: "SUPPLIER_CREDIT_VERIFIED",
  RECOVERY_RECONCILED: "RECOVERY_RECONCILED",
  RETURN_CLOSED: "RETURN_CLOSED",
});

const STATE_TRANSITIONS = Object.freeze({
  DRAFT: ["REQUESTED", "CANCELLED"],
  REQUESTED: ["APPROVED", "REJECTED", "CANCELLED"],
  APPROVED: ["RETURN_LABEL_REQUIRED", "IN_TRANSIT", "RECEIVED", "CANCELLED"],
  RETURN_LABEL_REQUIRED: ["IN_TRANSIT", "CANCELLED"],
  IN_TRANSIT: ["RECEIVED", "CANCELLED"],
  RECEIVED: ["INSPECTION_REQUIRED", "INSPECTED", "CANCELLED"],
  INSPECTION_REQUIRED: ["INSPECTED", "CANCELLED"],
  INSPECTED: ["REFUND_PENDING", "SUPPLIER_RECOVERY_PENDING", "CANCELLED"],
  REFUND_PENDING: ["REFUNDED", "CANCELLED"],
  REFUNDED: ["SUPPLIER_RECOVERY_PENDING", "SUPPLIER_CREDIT_PENDING", "CLOSED"],
  SUPPLIER_RECOVERY_PENDING: [
    "SUPPLIER_REFUND_CONFIRMED",
    "SUPPLIER_CREDIT_PENDING",
    "CLOSED",
  ],
  SUPPLIER_CREDIT_PENDING: ["SUPPLIER_CREDIT_CONFIRMED", "CLOSED"],
  SUPPLIER_REFUND_CONFIRMED: ["CLOSED"],
  SUPPLIER_CREDIT_CONFIRMED: ["CLOSED"],
  CLOSED: [],
  REJECTED: [],
  CANCELLED: [],
});

module.exports = {
  RETURN_STATES,
  ITEM_CONDITIONS,
  RETURN_REASONS,
  LIABILITY_TYPES,
  SUPPLIER_RECOVERY_STATUS,
  CREDIT_NOTE_STATUS,
  RETURN_SHIPPING_PAID_BY,
  SUPPLIER_RECOVERY_EVENT_TYPES,
  AUDIT_ACTIONS,
  STATE_TRANSITIONS,
};
