const ERROR_CODES = Object.freeze({
  RETURN_NOT_FOUND: "RETURN_NOT_FOUND",
  RETURN_ALREADY_EXISTS: "RETURN_ALREADY_EXISTS",
  RETURN_INVALID_STATE: "RETURN_INVALID_STATE",
  REFUND_EXECUTION_BLOCKED: "REFUND_EXECUTION_BLOCKED",
  SUPPLIER_LIVE_DISABLED: "SUPPLIER_LIVE_DISABLED",
  SUPPLIER_RECOVERY_INVALID: "SUPPLIER_RECOVERY_INVALID",
  CREDIT_NOTE_DUPLICATE: "CREDIT_NOTE_DUPLICATE",
  CREDIT_NOTE_UNVERIFIED: "CREDIT_NOTE_UNVERIFIED",
  INSPECTION_REQUIRED: "INSPECTION_REQUIRED",
  LIABILITY_REVIEW_REQUIRED: "LIABILITY_REVIEW_REQUIRED",
  RECONCILIATION_BLOCKED: "RECONCILIATION_BLOCKED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
});

function createReturnRecoveryError(code, message, details = {}) {
  const err = new Error(message || code);
  err.code = code;
  err.details = details;
  err.returnRecoveryError = { code, message: message || code, details };
  return err;
}

module.exports = { ERROR_CODES, createReturnRecoveryError };
