/** Part 5 — Job types, check statuses, integration health */

const JOB_TYPES = Object.freeze({
  PRODUCT_SYNC: "PRODUCT_SYNC",
  PRICE_SYNC: "PRICE_SYNC",
  STOCK_SYNC: "STOCK_SYNC",
  SUPPLIER_SYNC: "SUPPLIER_SYNC",
  CATEGORY_READINESS: "CATEGORY_READINESS",
  AI_TASK: "AI_TASK",
  NOTIFICATION: "NOTIFICATION",
  SYSTEM_HEALTH: "SYSTEM_HEALTH",
  PRODUCT_IMPORT: "PRODUCT_IMPORT",
  PRODUCT_VALIDATE: "PRODUCT_VALIDATE",
  PRODUCT_NORMALIZE: "PRODUCT_NORMALIZE",
  PRODUCT_MAPPING: "PRODUCT_MAPPING",
  CATALOG_SYNC: "CATALOG_SYNC",
});

const JOB_STATUS = Object.freeze({
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  RETRYING: "RETRYING",
  CANCELLED: "CANCELLED",
  DEAD_LETTER: "DEAD_LETTER",
});

const JOB_PRIORITY = Object.freeze({
  CRITICAL: "CRITICAL",
  HIGH: "HIGH",
  NORMAL: "NORMAL",
  LOW: "LOW",
});

const PRIORITY_WEIGHT = Object.freeze({
  CRITICAL: 4,
  HIGH: 3,
  NORMAL: 2,
  LOW: 1,
});

const SCHEDULE_TYPE = Object.freeze({
  ONE_TIME: "ONE_TIME",
  RECURRING: "RECURRING",
  DELAYED: "DELAYED",
});

const CHECK_STATUS = Object.freeze({
  PASS: "PASS",
  FAIL: "FAIL",
  WARNING: "WARNING",
  UNKNOWN: "UNKNOWN",
});

const READINESS_OVERALL = Object.freeze({
  READY: "READY",
  NOT_READY: "NOT_READY",
  BLOCKED: "BLOCKED",
  DRAFT: "DRAFT",
});

const INTEGRATION_HEALTH = Object.freeze({
  CONNECTED: "CONNECTED",
  DEGRADED: "DEGRADED",
  DISCONNECTED: "DISCONNECTED",
  ERROR: "ERROR",
});

const WORKER_STATE = Object.freeze({
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  STOPPED: "STOPPED",
});

const FAILURE_KIND = Object.freeze({
  TIMEOUT: "TIMEOUT",
  CRASH: "CRASH",
  NETWORK: "NETWORK",
  PROVIDER: "PROVIDER",
  DATABASE: "DATABASE",
  VALIDATION: "VALIDATION",
  UNKNOWN: "UNKNOWN",
});

const SUPPLIER_CAPABILITIES = Object.freeze({
  AUTHENTICATE: "authenticate",
  PRODUCTS: "products",
  PRICES: "prices",
  STOCK: "stock",
  AVAILABILITY: "availability",
  CATEGORIES: "categories",
  ORDERS: "orders",
  HEALTH_CHECK: "healthCheck",
});

const DATA_FORMAT = Object.freeze({
  REST: "REST",
  XML: "XML",
  CSV: "CSV",
  JSON: "JSON",
});

const DEFAULT_JOB_TIMEOUT_MS = Number(process.env.BUZZARD_JOB_TIMEOUT_MS) || 120_000;
const DEFAULT_LOCK_TTL_MS = Number(process.env.BUZZARD_JOB_LOCK_TTL_MS) || 300_000;
const DEFAULT_MAX_RETRIES = 3;

module.exports = {
  JOB_TYPES,
  JOB_STATUS,
  JOB_PRIORITY,
  PRIORITY_WEIGHT,
  SCHEDULE_TYPE,
  CHECK_STATUS,
  READINESS_OVERALL,
  INTEGRATION_HEALTH,
  WORKER_STATE,
  FAILURE_KIND,
  SUPPLIER_CAPABILITIES,
  DATA_FORMAT,
  DEFAULT_JOB_TIMEOUT_MS,
  DEFAULT_LOCK_TTL_MS,
  DEFAULT_MAX_RETRIES,
};
