/**
 * Part 16 — Product staging lifecycle (supplier-neutral, pre-PIM buffer).
 * Distinct from pim_core_products.status — staging never auto-promotes to PUBLIC/SALES.
 */
const STAGING_LIFECYCLE = Object.freeze({
  DISCOVERED: "DISCOVERED",
  IMPORTED: "IMPORTED",
  VALIDATION_PENDING: "VALIDATION_PENDING",
  VALIDATED: "VALIDATED",
  BLOCKED: "BLOCKED",
  INVALID: "INVALID",
  REJECTED: "REJECTED",
  PROMOTED: "PROMOTED",
});

const STAGING_TRANSITIONS = Object.freeze({
  DISCOVERED: ["IMPORTED", "VALIDATION_PENDING", "BLOCKED", "REJECTED"],
  IMPORTED: ["VALIDATION_PENDING", "BLOCKED", "REJECTED"],
  VALIDATION_PENDING: ["VALIDATED", "BLOCKED", "INVALID", "REJECTED"],
  VALIDATED: ["PROMOTED", "BLOCKED", "REJECTED"],
  BLOCKED: ["VALIDATION_PENDING", "REJECTED"],
  INVALID: ["VALIDATION_PENDING", "REJECTED"],
  REJECTED: [],
  PROMOTED: [],
});

/** PIM Core publication ladder (visibility + status — sales remains independent). */
const PUBLICATION_LADDER = Object.freeze([
  { step: "IMPORTED", status: "IMPORTED", visibility: "HIDDEN" },
  { step: "VALIDATED", status: "VALIDATING", visibility: "HIDDEN" },
  { step: "READY", status: "READY", visibility: "HIDDEN" },
  { step: "CATALOG", status: "READY", visibility: "CATALOG" },
  { step: "PUBLIC", status: "READY", visibility: "PUBLIC" },
]);

const BLOCKING_CODES = Object.freeze({
  GTIN_MISSING: "GTIN_MISSING",
  GTIN_INVALID: "GTIN_INVALID",
  GTIN_UNVERIFIED: "GTIN_UNVERIFIED",
  MPN_MISSING: "MPN_MISSING",
  MPN_INVALID: "MPN_INVALID",
  SUPPLIER_MISSING: "SUPPLIER_MISSING",
  SUPPLIER_TEST_ONLY: "SUPPLIER_TEST_ONLY",
  SUPPLIER_UNKNOWN: "SUPPLIER_UNKNOWN",
  IMAGE_MISSING: "IMAGE_MISSING",
  IMAGE_INVALID: "IMAGE_INVALID",
  PRICE_INVALID: "PRICE_INVALID",
  PRICE_MISSING: "PRICE_MISSING",
  STOCK_INVALID: "STOCK_INVALID",
  CURRENCY_INVALID: "CURRENCY_INVALID",
  CATEGORY_UNKNOWN: "CATEGORY_UNKNOWN",
  CATEGORY_UNMAPPED: "CATEGORY_UNMAPPED",
  DUPLICATE: "DUPLICATE",
  DEMO_PRODUCT: "DEMO_PRODUCT",
  BRAND_MISSING: "BRAND_MISSING",
  TITLE_MISSING: "TITLE_MISSING",
  PROVENANCE_MISSING: "PROVENANCE_MISSING",
  FITMENT_UNVERIFIED: "FITMENT_UNVERIFIED",
});

function canStagingTransition(from, to) {
  return (STAGING_TRANSITIONS[from] || []).includes(to);
}

module.exports = {
  STAGING_LIFECYCLE,
  STAGING_TRANSITIONS,
  PUBLICATION_LADDER,
  BLOCKING_CODES,
  canStagingTransition,
};
