/**
 * Part 21 — Security / observability readiness constants.
 */
const AUDIT_FINDING_SEVERITY = Object.freeze({
  INFO: "INFO",
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

const SECURITY_READINESS_GATES = Object.freeze([
  "AUTHENTICATION",
  "AUTHORIZATION",
  "API_PROTECTION",
  "SECURITY_HEADERS",
  "SECRET_HANDLING",
  "PRODUCTION_SAFETY",
  "PAYMENT_SAFETY",
  "SUPPLIER_SAFETY",
  "CONFIG_VALIDATION",
  "AUDIT_LOGGING",
]);

const INCIDENT_CATEGORY = Object.freeze({
  SECURITY: "SECURITY",
  OPERATIONS: "OPERATIONS",
  CONFIG: "CONFIG",
  INFRASTRUCTURE: "INFRASTRUCTURE",
  BACKUP: "BACKUP",
  PAYMENTS: "PAYMENTS",
  SUPPLIER: "SUPPLIER",
});

const INCIDENT_RESOLUTION = Object.freeze({
  OPEN: "OPEN",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  RESOLVED: "RESOLVED",
});

const ALERT_CHANNEL = Object.freeze({
  INTERNAL: "INTERNAL",
  SMTP: "SMTP",
  WEBHOOK: "WEBHOOK",
});

const ALERT_CHANNEL_STATUS = Object.freeze({
  CONFIGURED: "CONFIGURED",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  CONDITION: "CONDITION",
});

module.exports = {
  AUDIT_FINDING_SEVERITY,
  SECURITY_READINESS_GATES,
  INCIDENT_CATEGORY,
  INCIDENT_RESOLUTION,
  ALERT_CHANNEL,
  ALERT_CHANNEL_STATUS,
};
