const FALLBACK = {
  STT_PROVIDER_NOT_CONFIGURED: "TEXT_FALLBACK",
  TTS_PROVIDER_NOT_CONFIGURED: "TEXT_FALLBACK",
  VOICE_DISABLED: "TEXT_FALLBACK",
  AVATAR_PROVIDER_NOT_CONFIGURED: "CSS_3D_FALLBACK",
  AVATAR_PROVIDER_NOT_WIRED: "CSS_3D_FALLBACK",
  AVATAR_NOT_LIVE: "CSS_3D_FALLBACK",
  WEBRTC_ICE_NOT_CONFIGURED: "NO_MEDIA",
  PHONE_PROVIDER_NOT_CONFIGURED: "PHONE_UNAVAILABLE",
  CIRCUIT_OPEN: "PROVIDER_UNAVAILABLE",
  RATE_LIMITED: "PROVIDER_UNAVAILABLE",
  TIMEOUT: "PROVIDER_UNAVAILABLE",
  PROVIDER_500: "PROVIDER_UNAVAILABLE",
  PROVIDER_429: "PROVIDER_UNAVAILABLE",
  NETWORK_INTERRUPTION: "RECONNECT",
  AVATAR_DISCONNECT: "CSS_3D_FALLBACK",
  WEBRTC_DISCONNECT: "NO_MEDIA",
};

function recoverFromFailure(code) {
  return {
    code,
    fallback: FALLBACK[code] || "PROVIDER_UNAVAILABLE",
    live: false,
    REAL_AVATAR_ACTIVE: false,
    REAL_VIDEO_ACTIVE: false,
    REAL_LIP_SYNC_ACTIVE: false,
    REAL_STT_ACTIVE: false,
    REAL_TTS_ACTIVE: false,
    REAL_PHONE_ACTIVE: false,
    WEBRTC_MEDIA_ACTIVE: false,
  };
}

module.exports = { recoverFromFailure, FALLBACK };
