export type AdminLabelLocale = "de" | "en" | "tr" | "ar";

export const SUPPLIER_ADMIN_LABELS: Record<
  AdminLabelLocale,
  Record<string, string>
> = {
  de: {
    title: "Lieferanten-Operations",
    overview: "Übersicht",
    suppliers: "Lieferanten",
    total: "Gesamt",
    active: "Aktiv",
    healthy: "Gesund",
    degraded: "Eingeschränkt",
    unhealthy: "Ungesund",
    disabled: "Deaktiviert",
    syncing: "Synchronisiert",
    lastSuccess: "Letzter Erfolg",
    lastFailure: "Letzter Fehler",
    productsProcessed: "Produkte verarbeitet",
    offersUpdated: "Angebote aktualisiert",
    stockUpdated: "Bestand aktualisiert",
    priceUpdated: "Preise aktualisiert",
    name: "Name",
    connector: "Connector",
    health: "Health",
    syncStatus: "Sync-Status",
    reliability: "Zuverlässigkeit",
    markets: "Märkte",
    capabilities: "Fähigkeiten",
    detail: "Details",
    enable: "Aktivieren",
    disable: "Deaktivieren",
    manualSync: "Manueller Sync",
    cursor: "Cursor",
    resetCursor: "Cursor zurücksetzen",
    confirmReset: "Bestätigen",
    loading: "Laden…",
    error: "Fehler",
    noData: "Keine Daten",
    connection: "Verbindung",
    connectionStatus: "Verbindungsstatus",
    environment: "Umgebung",
    testConnection: "Verbindung testen",
    testSync: "Test-Sync",
    lastHealthCheck: "Letzter Health-Check",
    liveReadSync: "Live-Read-Sync",
    dataQuality: "Datenqualität",
    offerCount: "Angebote",
    productCount: "Produkte",
    orderSandbox: "Order-Sandbox",
    realSupplierOrderNetwork: "Echtes Supplier-Order-Netzwerk",
    networkDisabled: "DEAKTIVIERT",
    sandboxTest: "Sandbox-Order testen",
    lastSandboxOrder: "Letzte Sandbox-Order",
    sandboxReference: "Sandbox-Referenz",
    idempotencyKey: "Idempotency-Key",
  },
  en: {
    title: "Supplier Operations",
    overview: "Overview",
    suppliers: "Suppliers",
    total: "Total",
    active: "Active",
    healthy: "Healthy",
    degraded: "Degraded",
    unhealthy: "Unhealthy",
    disabled: "Disabled",
    syncing: "Syncing",
    lastSuccess: "Last success",
    lastFailure: "Last failure",
    productsProcessed: "Products processed",
    offersUpdated: "Offers updated",
    stockUpdated: "Stock updated",
    priceUpdated: "Prices updated",
    name: "Name",
    connector: "Connector",
    health: "Health",
    syncStatus: "Sync status",
    reliability: "Reliability",
    markets: "Markets",
    capabilities: "Capabilities",
    detail: "Details",
    enable: "Enable",
    disable: "Disable",
    manualSync: "Manual sync",
    cursor: "Cursor",
    resetCursor: "Reset cursor",
    confirmReset: "Confirm",
    loading: "Loading…",
    error: "Error",
    noData: "No data",
    connection: "Connection",
    connectionStatus: "Connection status",
    environment: "Environment",
    testConnection: "Test connection",
    testSync: "Test sync",
    lastHealthCheck: "Last health check",
    liveReadSync: "Live read sync",
    dataQuality: "Data quality",
    offerCount: "Offers",
    productCount: "Products",
    orderSandbox: "Order sandbox",
    realSupplierOrderNetwork: "Real supplier order network",
    networkDisabled: "DISABLED",
    sandboxTest: "Test sandbox order",
    lastSandboxOrder: "Last sandbox order",
    sandboxReference: "Sandbox reference",
    idempotencyKey: "Idempotency key",
  },
  tr: {
    title: "Tedarikçi Operasyonları",
    overview: "Genel Bakış",
    suppliers: "Tedarikçiler",
    total: "Toplam",
    active: "Aktif",
    healthy: "Sağlıklı",
    degraded: "Düşük performans",
    unhealthy: "Sağlıksız",
    disabled: "Devre dışı",
    syncing: "Senkronize ediliyor",
    lastSuccess: "Son başarı",
    lastFailure: "Son hata",
    productsProcessed: "İşlenen ürünler",
    offersUpdated: "Güncellenen teklifler",
    stockUpdated: "Güncellenen stok",
    priceUpdated: "Güncellenen fiyat",
    name: "Ad",
    connector: "Bağlayıcı",
    health: "Sağlık",
    syncStatus: "Sync durumu",
    reliability: "Güvenilirlik",
    markets: "Pazarlar",
    capabilities: "Yetenekler",
    detail: "Detay",
    enable: "Etkinleştir",
    disable: "Devre dışı bırak",
    manualSync: "Manuel sync",
    cursor: "Cursor",
    resetCursor: "Cursor sıfırla",
    confirmReset: "Onayla",
    loading: "Yükleniyor…",
    error: "Hata",
    noData: "Veri yok",
    connection: "Bağlantı",
    connectionStatus: "Bağlantı durumu",
    environment: "Ortam",
    testConnection: "Bağlantıyı test et",
    testSync: "Test sync",
    lastHealthCheck: "Son health check",
    liveReadSync: "Canlı okuma sync",
    dataQuality: "Veri kalitesi",
    offerCount: "Teklifler",
    productCount: "Ürünler",
    orderSandbox: "Sipariş sandbox",
    realSupplierOrderNetwork: "Gerçek tedarikçi sipariş ağı",
    networkDisabled: "DEVRE DIŞI",
    sandboxTest: "Sandbox siparişi test et",
    lastSandboxOrder: "Son sandbox siparişi",
    sandboxReference: "Sandbox referansı",
    idempotencyKey: "Idempotency anahtarı",
  },
  ar: {
    title: "عمليات الموردين",
    overview: "نظرة عامة",
    suppliers: "الموردون",
    total: "الإجمالي",
    active: "نشط",
    healthy: "سليم",
    degraded: "متدهور",
    unhealthy: "غير سليم",
    disabled: "معطل",
    syncing: "جاري المزامنة",
    lastSuccess: "آخر نجاح",
    lastFailure: "آخر فشل",
    productsProcessed: "المنتجات المعالجة",
    offersUpdated: "العروض المحدثة",
    stockUpdated: "المخزون المحدث",
    priceUpdated: "الأسعار المحدثة",
    name: "الاسم",
    connector: "الموصل",
    health: "الحالة",
    syncStatus: "حالة المزامنة",
    reliability: "الموثوقية",
    markets: "الأسواق",
    capabilities: "القدرات",
    detail: "التفاصيل",
    enable: "تفعيل",
    disable: "تعطيل",
    manualSync: "مزامنة يدوية",
    cursor: "المؤشر",
    resetCursor: "إعادة تعيين المؤشر",
    confirmReset: "تأكيد",
    loading: "جاري التحميل…",
    error: "خطأ",
    noData: "لا توجد بيانات",
    connection: "الاتصال",
    connectionStatus: "حالة الاتصال",
    environment: "البيئة",
    testConnection: "اختبار الاتصال",
    testSync: "مزامنة تجريبية",
    lastHealthCheck: "آخر فحص صحة",
    liveReadSync: "مزامنة القراءة المباشرة",
    dataQuality: "جودة البيانات",
    offerCount: "العروض",
    productCount: "المنتجات",
    orderSandbox: "صندوق طلبات المورد",
    realSupplierOrderNetwork: "شبكة طلبات المورد الحقيقية",
    networkDisabled: "معطل",
    sandboxTest: "اختبار طلب sandbox",
    lastSandboxOrder: "آخر طلب sandbox",
    sandboxReference: "مرجع sandbox",
    idempotencyKey: "مفتاح idempotency",
  },
};

export function getSupplierAdminLabels(locale: AdminLabelLocale = "de") {
  return SUPPLIER_ADMIN_LABELS[locale] || SUPPLIER_ADMIN_LABELS.de;
}
