export type AdminLabelLocale = "de" | "en" | "tr" | "ar";

export const SUPPLIER_ADMIN_LABELS: Record<
  AdminLabelLocale,
  Record<string, string>
> = {
  de: {
    title: "Lieferanten-Operations",
    overview: "Übersicht",
    suppliers: "Lieferanten",
    total: "Gesamt",
    active: "Aktiv",
    healthy: "Gesund",
    degraded: "Eingeschränkt",
    unhealthy: "Ungesund",
    disabled: "Deaktiviert",
    syncing: "Synchronisiert",
    lastSuccess: "Letzter Erfolg",
    lastFailure: "Letzter Fehler",
    productsProcessed: "Produkte verarbeitet",
    offersUpdated: "Angebote aktualisiert",
    stockUpdated: "Bestand aktualisiert",
    priceUpdated: "Preise aktualisiert",
    name: "Name",
    connector: "Connector",
    health: "Health",
    syncStatus: "Sync-Status",
    reliability: "Zuverlässigkeit",
    markets: "Märkte",
    capabilities: "Fähigkeiten",
    detail: "Details",
    enable: "Aktivieren",
    disable: "Deaktivieren",
    manualSync: "Manueller Sync",
    cursor: "Cursor",
    resetCursor: "Cursor zurücksetzen",
    confirmReset: "Bestätigen",
    loading: "Laden…",
    error: "Fehler",
    noData: "Keine Daten",
  },
  en: {
    title: "Supplier Operations",
    overview: "Overview",
    suppliers: "Suppliers",
    total: "Total",
    active: "Active",
    healthy: "Healthy",
    degraded: "Degraded",
    unhealthy: "Unhealthy",
    disabled: "Disabled",
    syncing: "Syncing",
    lastSuccess: "Last success",
    lastFailure: "Last failure",
    productsProcessed: "Products processed",
    offersUpdated: "Offers updated",
    stockUpdated: "Stock updated",
    priceUpdated: "Prices updated",
    name: "Name",
    connector: "Connector",
    health: "Health",
    syncStatus: "Sync status",
    reliability: "Reliability",
    markets: "Markets",
    capabilities: "Capabilities",
    detail: "Details",
    enable: "Enable",
    disable: "Disable",
    manualSync: "Manual sync",
    cursor: "Cursor",
    resetCursor: "Reset cursor",
    confirmReset: "Confirm",
    loading: "Loading…",
    error: "Error",
    noData: "No data",
  },
  tr: {
    title: "Tedarikçi Operasyonları",
    overview: "Genel Bakış",
    suppliers: "Tedarikçiler",
    total: "Toplam",
    active: "Aktif",
    healthy: "Sağlıklı",
    degraded: "Düşük performans",
    unhealthy: "Sağlıksız",
    disabled: "Devre dışı",
    syncing: "Senkronize ediliyor",
    lastSuccess: "Son başarı",
    lastFailure: "Son hata",
    productsProcessed: "İşlenen ürünler",
    offersUpdated: "Güncellenen teklifler",
    stockUpdated: "Güncellenen stok",
    priceUpdated: "Güncellenen fiyat",
    name: "Ad",
    connector: "Bağlayıcı",
    health: "Sağlık",
    syncStatus: "Sync durumu",
    reliability: "Güvenilirlik",
    markets: "Pazarlar",
    capabilities: "Yetenekler",
    detail: "Detay",
    enable: "Etkinleştir",
    disable: "Devre dışı bırak",
    manualSync: "Manuel sync",
    cursor: "Cursor",
    resetCursor: "Cursor sıfırla",
    confirmReset: "Onayla",
    loading: "Yükleniyor…",
    error: "Hata",
    noData: "Veri yok",
  },
  ar: {
    title: "عمليات الموردين",
    overview: "نظرة عامة",
    suppliers: "الموردون",
    total: "الإجمالي",
    active: "نشط",
    healthy: "سليم",
    degraded: "متدهور",
    unhealthy: "غير سليم",
    disabled: "معطل",
    syncing: "جاري المزامنة",
    lastSuccess: "آخر نجاح",
    lastFailure: "آخر فشل",
    productsProcessed: "المنتجات المعالجة",
    offersUpdated: "العروض المحدثة",
    stockUpdated: "المخزون المحدث",
    priceUpdated: "الأسعار المحدثة",
    name: "الاسم",
    connector: "الموصل",
    health: "الحالة",
    syncStatus: "حالة المزامنة",
    reliability: "الموثوقية",
    markets: "الأسواق",
    capabilities: "القدرات",
    detail: "التفاصيل",
    enable: "تفعيل",
    disable: "تعطيل",
    manualSync: "مزامنة يدوية",
    cursor: "المؤشر",
    resetCursor: "إعادة تعيين المؤشر",
    confirmReset: "تأكيد",
    loading: "جاري التحميل…",
    error: "خطأ",
    noData: "لا توجد بيانات",
  },
};

export function getSupplierAdminLabels(locale: AdminLabelLocale = "de") {
  return SUPPLIER_ADMIN_LABELS[locale] || SUPPLIER_ADMIN_LABELS.de;
}
