/**
 * A–G product source registry. Read/write paths that exist in this repo.
 * Does not invent missing stores or claim continuous sync.
 */
const SOURCE_CATALOG = Object.freeze({
  A: {
    source: "A",
    name: "Admin JSON catalog",
    store: "productStore",
    collection: "data/buzzard_products.json",
    table: null,
    api: "/api/admin/products",
    write: "adminCatalogPlugin + productStore",
    read: "productStore.listProducts / getProductById",
    productId: "prod-*",
    sku: "sku",
    ean: "ean_gtin",
    brand: "brand",
    category: "category",
    price: "price",
    inventory: "stock",
    translation: null,
    status: "LEGACY_WRITE",
  },
  B: {
    source: "B",
    name: "PIM v1 products",
    store: "pimCatalogPlugin",
    collection: null,
    table: "pim_products",
    api: "pim catalog plugin routes",
    write: "pimCatalogPlugin",
    read: "pim_products SELECT",
    productId: "INTEGER id",
    sku: "sku",
    ean: "ean",
    brand: "brand_id",
    category: "category_id",
    price: "price",
    inventory: "stock",
    translation: null,
    status: "LEGACY_WRITE",
  },
  C: {
    source: "C",
    name: "PIM v30 products",
    store: "productCatalogPim",
    collection: null,
    table: "pim30_products",
    api: "productCatalogPimPlugin routes",
    write: "productCatalogPimPlugin",
    read: "pim30_products SELECT",
    productId: "INTEGER id",
    sku: "sku",
    ean: "ean",
    brand: "brand_id",
    category: "category_id",
    price: "price",
    inventory: "stock",
    translation: "pim30_product_translations",
    status: "LEGACY_WRITE",
  },
  D: {
    source: "D",
    name: "PIM core (canonical target)",
    store: "productCore",
    collection: null,
    table: "pim_core_products",
    api: "product core / catalogReadService",
    write: "productCore.createProduct / updateProduct",
    read: "productCore.getProduct / listProducts",
    productId: "pim_prod_* TEXT",
    sku: "sku",
    ean: "ean / gtin",
    brand: "brand_id",
    category: "taxonomy_category_id",
    price: "price",
    inventory: "stock",
    translation: null,
    status: "CANONICAL_TARGET",
  },
  E: {
    source: "E",
    name: "SEO catalog products",
    store: "catalogSeoPlugin",
    collection: null,
    table: "products",
    api: "catalog SEO plugin routes",
    write: "catalogSeoPlugin",
    read: "products SELECT",
    productId: "INTEGER id",
    sku: "sku / slug",
    ean: null,
    brand: null,
    category: "category_id",
    price: "price",
    inventory: "stock",
    translation: null,
    status: "LEGACY_WRITE",
  },
  F: {
    source: "F",
    name: "Supplier feed products",
    store: "supplier adapters",
    collection: null,
    table: "supplier_products",
    api: "supplier hub / mappings",
    write: "supplier import (not live in this phase)",
    read: "supplier_products SELECT",
    productId: "supplier_id + supplier_sku",
    sku: "product_sku / buzzard_sku / supplier_sku",
    ean: "ean",
    brand: "brand",
    category: "category",
    price: "cost_eur",
    inventory: "stock",
    translation: null,
    status: "FEED_ONLY",
  },
  G: {
    source: "G",
    name: "Marketplace SKU map",
    store: "marketplace_product_map",
    collection: null,
    table: "marketplace_product_map",
    api: "marketplace hub",
    write: "marketplace listing adapters (not live in this phase)",
    read: "marketplace_product_map SELECT",
    productId: "marketplace_sku string",
    sku: "marketplace_sku",
    ean: null,
    brand: null,
    category: null,
    price: null,
    inventory: null,
    translation: null,
    status: "MAPPING_ONLY",
  },
});

function listSources() {
  return Object.values(SOURCE_CATALOG);
}

function sourceMatrix() {
  return listSources().map((s) => ({
    SOURCE: s.source,
    READ: s.read,
    WRITE: s.write,
    PRODUCT_ID: s.productId,
    SKU: s.sku,
    EAN: s.ean || "—",
    STATUS: s.status,
  }));
}

module.exports = { SOURCE_CATALOG, listSources, sourceMatrix };
