const PERMISSIONS = {
  administrator: ["*"],
  super_admin: ["*"],
  admin: [
    "users.read",
    "users.write",
    "categories.read",
    "categories.write",
    "categories.publish",
    "products.read",
    "products.write",
    "orders.read",
    "orders.write",
    "ai.read",
    "ai.assign",
    "ai.execute",
    "system.read",
    "system.configure",
    "security.read",
    "security.manage",
    "audit.read",
    "integrations.read",
    "integrations.manage",
    "returns.read",
    "returns.write",
    "returns.approve",
    "returns.inspect",
    "returns.refund",
    "returns.supplier_recovery",
    "returns.close",
    "fulfillment.read",
    "fulfillment.reconcile",
    "fulfillment.incident.read",
    "fulfillment.incident.resolve",
    "supplier-order.readiness.read",
    "supplier-order.readiness.request",
    "supplier-order.readiness.approve",
    "supplier-order.readiness.reject",
    "supplier-order.readiness.admin",
    "supplier-order.rehearsal.read",
    "supplier-order.rehearsal.run",
    "supplier-production-validation.read",
    "supplier-production-validation.run",
    "supplier-production-validation.admin",
    "supplier-order.activation.read",
    "supplier-order.activation.preflight",
    "supplier-order.activation.request",
    "supplier-order.activation.approve",
    "supplier-order.activation.arm",
    "supplier-order.activation.confirm",
    "supplier-order.activation.revoke",
    "supplier-order.activation.admin",
    "supplier-production-order-validation.read",
    "supplier-production-order-validation.run",
    "supplier-production-order-validation.admin",
    "supplier-production-order-arming.read",
    "supplier-production-order-arming.request",
    "supplier-production-order-arming.approve",
    "supplier-production-order-arming.arm",
    "supplier-production-order-arming.disarm",
    "supplier-production-order-arming.admin",
  ],
  catalog_manager: [
    "products.read",
    "products.write",
    "categories.read",
    "categories.write",
    "categories.publish",
    "suppliers.read",
    "sync.read",
    "sync.run",
    "imports.run",
    "audit.read",
    "analytics.read",
    "analytics.export",
    "seo.read",
    "seo.write",
    "automation.read",
    "ai.read",
  ],
  order_manager: [
    "orders.read",
    "orders.write",
    "returns.read",
    "returns.write",
    "returns.approve",
    "returns.inspect",
    "returns.refund",
    "returns.supplier_recovery",
    "returns.close",
    "logistics.read",
    "logistics.write",
    "fulfillment.read",
    "fulfillment.reconcile",
    "fulfillment.incident.read",
    "fulfillment.incident.resolve",
    "supplier-order.readiness.read",
    "supplier-order.readiness.request",
    "supplier-order.readiness.approve",
    "supplier-order.readiness.reject",
    "supplier-order.rehearsal.read",
    "supplier-order.rehearsal.run",
    "supplier-production-validation.read",
    "supplier-production-validation.run",
    "supplier-order.activation.read",
    "supplier-order.activation.preflight",
    "supplier-order.activation.request",
    "supplier-order.activation.approve",
    "supplier-order.activation.arm",
    "supplier-production-order-validation.read",
    "supplier-production-order-validation.run",
    "supplier-production-order-arming.read",
    "supplier-production-order-arming.request",
    "supplier-production-order-arming.approve",
    "supplier-production-order-arming.arm",
    "products.read",
    "audit.read",
    "analytics.read",
    "analytics.export",
    "automation.read",
    "automation.run",
    "ai.read",
  ],
  staff: [
    "products.read",
    "categories.read",
    "orders.read",
    "ai.read",
    "audit.read",
    "system.read",
  ],
  ai_agent: ["ai.read", "ai.execute"],
  read_only: [
    "products.read",
    "suppliers.read",
    "sync.read",
    "orders.read",
    "logistics.read",
    "categories.read",
    "audit.read",
    "analytics.read",
    "automation.read",
    "ai.read",
    "system.read",
    "security.read",
  ],
};

function can(role, permission) {
  const normalized = role === "administrator" ? "super_admin" : role;
  const allowed = PERMISSIONS[normalized] || PERMISSIONS[role] || [];
  if (allowed.includes("*")) return true;
  return allowed.includes(permission);
}

function aiCanExecute(employeePermissions, requiredPermission) {
  if (!requiredPermission) return true;
  if (!Array.isArray(employeePermissions)) return false;
  if (employeePermissions.includes("*")) return true;
  return employeePermissions.includes(requiredPermission);
}

function requirePermission(req, res, permission) {
  if (!req.adminUser) return false;
  if (!can(req.adminUser.role, permission)) {
    res.status(403).json({ success: false, errorKey: "admin.auth.forbidden" });
    return false;
  }
  return true;
}

module.exports = { can, requirePermission, PERMISSIONS, aiCanExecute };
